services:
  cron_python_app:
    build: .
    volumes:
      - ./cron_logs:/var/log # Mount a volume to persist logs on the host
      - ./data:/var/data 

    ports:
      - '8001:8001'

    environment:
      - TZ=Etc/UTC
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      - AWS_REGION=${AWS_REGION} 
